name: tvtk-auto-update
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.PERSONAL_ACCESSTOKEN }}
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install Linux packages for Qt5 support
      run: |
        sudo apt-get update
        sudo apt-get install qt5-default
        sudo apt-get install libxkbcommon-x11-0
        sudo apt-get install libxcb-icccm4
        sudo apt-get install libxcb-image0
        sudo apt-get install libxcb-keysyms1
        sudo apt-get install libxcb-randr0
        sudo apt-get install libxcb-render-util0
        sudo apt-get install libxcb-xinerama0
    - name: Install dependencies and local packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pyqt5
        python -m pip install numpy
        python -m pip install vtk==9.0.3
        python -m pip install pillow
        python -m pip install nose
        (cd mayavi; git fetch origin; git checkout master; git reset --hard origin/master; git branch -a)
        pip3 install -r ./requirements.txt
    - name: update
      env:
        SPHINXINTL_TRANSIFEX_USERNAME: api
        SPHINXINTL_TRANSIFEX_PROJECT_NAME: tvtk-doc
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
      run: |
        sh ./locale/update.sh
    - name: git_config
      run: |
        git config --global user.email $GITHUB_REPOSITORY
        git config --global user.name $GITHUB_REPOSITORY
    - name: commit
      if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.ref, 'master')
      env:
        JOB_ID: ${{ steps.jobs.outputs.job_id }}
        HTML_URL: ${{ steps.jobs.outputs.html_url }}
      run: |
        git add .
        git commit --allow-empty -m "[ci skip] $JOB_ID
        $HTML_URL"
        git remote -v
        git remote add github git@github.com:$GITHUB_REPOSITORY.git
        git push github master
